<a href="https://colab.research.google.com/github/raz0208/Job-Analysis-/blob/main/Data_Analyst_Job_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Analyst Job Analysis**

The data used for this notebook is from LinkedIn jobs page. Only Key Responsibilities and job Requirments are slected as main data to this analys.

In [1]:
# Import Required Libraries
import pandas as pd
import re

In [3]:
# Read And Read The file
with open('DA-Skills.txt', 'r', encoding='utf-8') as f:
    content = f.read()

# Show some of the data in file
print(content[:500])

1)
Key Responsibilities
• Should be good at requirement gathering, documentation, presentation, and interaction with business stakeholders.
• Should be capable to interact with developers and testers to build complex logic in EDW.
• Technical knowledge of data models and database design.
• Good knowledge of Teradata/SQL and writing little complex scripts proficiently
• Develop and implement databases, data collection systems, data analytics and other strategies that optimize statistical efficie

In [4]:
# Split the content into jobs using the pattern like "1)", "2)", etc as objects.
# We look for a number followed by a parenthesis at the start of a line or after a newline.
jobs_raw = re.split(r'\n(?=\d+\))|^(?=\d+\))', content)
jobs = [j.strip() for j in jobs_raw if j.strip()]

# Clean job IDs if necessary (ensure we have 43)
print(f"Number of jobs found: {len(jobs)}")

Number of jobs found: 46

In [6]:
# Define a list of skills to look for based on pre-defined categories.
# I'll create a mapping of Skill Name -> Keywords to search for.
skill_keywords = {
    'Python': [r'\bPython\b'],
    'R': [r'\bR\b'],
    'Java': [r'\bJava\b'],
    'C++': [r'\bC\+\+\b'],
    'JavaScript': [r'\bJavaScript\b'],
    'Stata': [r'\bStata\b'],
    'Matlab': [r'\bMatlab\b'],
    'SQL': [r'\bSQL\b'],
    'T-SQL': [r'\bT-SQL\b'],
    'DAX': [r'\bDAX\b'],
    'Power Query': [r'Power Query'],
    'Tableau': [r'Tableau'],
    'Power BI': [r'Power BI'],
    'Looker': [r'Looker'],
    'Google Data Studio': [r'Google Data Studio', r'Looker Studio'],
    'Business Objects': [r'Business Objects'],
    'Thoughtspot': [r'Thoughtspot'],
    'Grafana': [r'Grafana'],
    'Apache Superset': [r'Superset'],
    'SQL Server': [r'SQL Server', r'SSMS'],
    'MySQL': [r'MySQL'],
    'Teradata': [r'Teradata'],
    'Snowflake': [r'Snowflake'],
    'Apache Spark': [r'Spark'],
    'Kafka': [r'Kafka'],
    'Hadoop': [r'Hadoop'],
    'Hive': [r'Hive'],
    'Impala': [r'Impala'],
    'AWS': [r'\bAWS\b'],
    'Azure': [r'\bAzure\b'],
    'Google Cloud': [r'Google Cloud', r'GCP', r'BigQuery'],
    'Machine Learning': [r'Machine Learning', r'\bML\b'],
    'Generative AI': [r'Generative AI', r'GenAI'],
    'NLP': [r'\bNLP\b', r'Natural Language Processing'],
    'Computer Vision': [r'Computer Vision'],
    'Deep Learning': [r'Deep Learning'],
    'Predictive Modeling': [r'Predictive Model'],
    'Excel': [r'Excel'],
    'Google Sheets': [r'Google Sheets'],
    'SAS': [r'\bSAS\b'],
    'Alteryx': [r'Alteryx'],
    'Dataiku': [r'Dataiku'],
    'Google Analytics': [r'Google Analytics', r'GA4'],
    'Adobe Analytics': [r'Adobe Analytics'],
    'Power Apps': [r'Power Apps'],
    'Power Automate': [r'Power Automate'],
    'ETL': [r'\bETL\b', r'\bELT\b'],
    'Data Cleaning': [r'Data Cleaning', r'Data Wrangling', r'Data Preprocessing'],
    'Data Mining': [r'Data Mining'],
    'Statistics': [r'Statist'],
    'Econometrics': [r'Econometric'],
    'Regression': [r'Regression'],
    'Analytical Thinking': [r'Analytical thinking', r'Analytical mindset', r'Analytical skills'],
    'Problem Solving': [r'Problem solving', r'Problem-solving'],
    'Communication': [r'Communication'],
    'Stakeholder Management': [r'Stakeholder'],
    'Presentation Skills': [r'Presentation'],
    'Attention to Detail': [r'Attention to detail', r'Precision'],
    'Agile': [r'Agile'],
    'Waterfall': [r'Waterfall'],
    'UAT': [r'\bUAT\b', r'User acceptance test'],
    'Requirement Gathering': [r'Requirement gathering'],
    'Documentation': [r'Documentation'],
    'SaaS Metrics': [r'SaaS', r'\bARR\b', r'\bMRR\b', r'\bCAC\b', r'\bLTV\b'],
    'Financial Modeling': [r'Financial model'],
    'GAAP/IFRS': [r'GAAP', r'IFRS']
}

skill_keywords

{'Python': ['\\bPython\\b'],
 'R': ['\\bR\\b'],
 'Java': ['\\bJava\\b'],
 'C++': ['\\bC\\+\\+\\b'],
 'JavaScript': ['\\bJavaScript\\b'],
 'Stata': ['\\bStata\\b'],
 'Matlab': ['\\bMatlab\\b'],
 'SQL': ['\\bSQL\\b'],
 'T-SQL': ['\\bT-SQL\\b'],
 'DAX': ['\\bDAX\\b'],
 'Power Query': ['Power Query'],
 'Tableau': ['Tableau'],
 'Power BI': ['Power BI'],
 'Looker': ['Looker'],
 'Google Data Studio': ['Google Data Studio', 'Looker Studio'],
 'Business Objects': ['Business Objects'],
 'Thoughtspot': ['Thoughtspot'],
 'Grafana': ['Grafana'],
 'Apache Superset': ['Superset'],
 'SQL Server': ['SQL Server', 'SSMS'],
 'MySQL': ['MySQL'],
 'Teradata': ['Teradata'],
 'Snowflake': ['Snowflake'],
 'Apache Spark': ['Spark'],
 'Kafka': ['Kafka'],
 'Hadoop': ['Hadoop'],
 'Hive': ['Hive'],
 'Impala': ['Impala'],
 'AWS': ['\\bAWS\\b'],
 'Azure': ['\\bAzure\\b'],
 'Google Cloud': ['Google Cloud', 'GCP', 'BigQuery'],
 'Machine Learning': ['Machine Learning', '\\bML\\b'],
 'Generative AI': ['Generative AI', 'GenAI'],
 'NLP': ['\\bNLP\\b', 'Natural Language Processing'],
 'Computer Vision': ['Computer Vision'],
 'Deep Learning': ['Deep Learning'],
 'Predictive Modeling': ['Predictive Model'],
 'Excel': ['Excel'],
 'Google Sheets': ['Google Sheets'],
 'SAS': ['\\bSAS\\b'],
 'Alteryx': ['Alteryx'],
 'Dataiku': ['Dataiku'],
 'Google Analytics': ['Google Analytics', 'GA4'],
 'Adobe Analytics': ['Adobe Analytics'],
 'Power Apps': ['Power Apps'],
 'Power Automate': ['Power Automate'],
 'ETL': ['\\bETL\\b', '\\bELT\\b'],
 'Data Cleaning': ['Data Cleaning', 'Data Wrangling', 'Data Preprocessing'],
 'Data Mining': ['Data Mining'],
 'Statistics': ['Statist'],
 'Econometrics': ['Econometric'],
 'Regression': ['Regression'],
 'Analytical Thinking': ['Analytical thinking',
  'Analytical mindset',
  'Analytical skills'],
 'Problem Solving': ['Problem solving', 'Problem-solving'],
 'Communication': ['Communication'],
 'Stakeholder Management': ['Stakeholder'],
 'Presentation Skills': ['Presentation'],
 'Attention to Detail': ['Attention to detail', 'Precision'],
 'Agile': ['Agile'],
 'Waterfall': ['Waterfall'],
 'UAT': ['\\bUAT\\b', 'User acceptance test'],
 'Requirement Gathering': ['Requirement gathering'],
 'Documentation': ['Documentation'],
 'SaaS Metrics': ['SaaS', '\\bARR\\b', '\\bMRR\\b', '\\bCAC\\b', '\\bLTV\\b'],
 'Financial Modeling': ['Financial model'],
 'GAAP/IFRS': ['GAAP', 'IFRS']}

In [9]:
# Initialize the data list
data = []

for i, job_text in enumerate(jobs):
    row = {'Job Description': f"Job {i+1}"}
    for skill, patterns in skill_keywords.items():
        found = 0
        for pattern in patterns:
            if re.search(pattern, job_text, re.IGNORECASE):
                found = 1
                break
        row[skill] = found
    data.append(row)

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv('skill_frequency_matrix.csv', index=False)

df.head()

,Job Description,Python,R,Java,C++,JavaScript,Stata,Matlab,SQL,T-SQL,...,Presentation Skills,Attention to Detail,Agile,Waterfall,UAT,Requirement Gathering,Documentation,SaaS Metrics,Financial Modeling,GAAP/IFRS
0,Job 1,0,0,0,0,1,0,0,1,0,...,1,1,1,1,1,1,1,0,0,0
1,Job 2,1,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2,Job 3,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Job 4,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Job 5,1,1,0,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 67 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Job Description         46 non-null     object
 1   Python                  46 non-null     int64
 2   R                       46 non-null     int64
 3   Java                    46 non-null     int64
 4   C++                     46 non-null     int64
 5   JavaScript              46 non-null     int64
 6   Stata                   46 non-null     int64
 7   Matlab                  46 non-null     int64
 8   SQL                     46 non-null     int64
 9   T-SQL                   46 non-null     int64
 10  DAX                     46 non-null     int64
 11  Power Query             46 non-null     int64
 12  Tableau                 46 non-null     int64
 13  Power BI                46 non-null     int64
 14  Looker                  46 non-null     int64
 15  Google Data Studio      46 non-null     int64
 16  Business Objects        46 non-null     int64
 17  Thoughtspot             46 non-null     int64
 18  Grafana                 46 non-null     int64
 19  Apache Superset         46 non-null     int64
 20  SQL Server              46 non-null     int64
 21  MySQL                   46 non-null     int64
 22  Teradata                46 non-null     int64
 23  Snowflake               46 non-null     int64
 24  Apache Spark            46 non-null     int64
 25  Kafka                   46 non-null     int64
 26  Hadoop                  46 non-null     int64
 27  Hive                    46 non-null     int64
 28  Impala                  46 non-null     int64
 29  AWS                     46 non-null     int64
 30  Azure                   46 non-null     int64
 31  Google Cloud            46 non-null     int64
 32  Machine Learning        46 non-null     int64
 33  Generative AI           46 non-null     int64
 34  NLP                     46 non-null     int64
 35  Computer Vision         46 non-null     int64
 36  Deep Learning           46 non-null     int64
 37  Predictive Modeling     46 non-null     int64
 38  Excel                   46 non-null     int64
 39  Google Sheets           46 non-null     int64
 40  SAS                     46 non-null     int64
 41  Alteryx                 46 non-null     int64
 42  Dataiku                 46 non-null     int64
 43  Google Analytics        46 non-null     int64
 44  Adobe Analytics         46 non-null     int64
 45  Power Apps              46 non-null     int64
 46  Power Automate          46 non-null     int64
 47  ETL                     46 non-null     int64
 48  Data Cleaning           46 non-null     int64
 49  Data Mining             46 non-null     int64
 50  Statistics              46 non-null     int64
 51  Econometrics            46 non-null     int64
 52  Regression              46 non-null     int64
 53  Analytical Thinking     46 non-null     int64
 54  Problem Solving         46 non-null     int64
 55  Communication           46 non-null     int64
 56  Stakeholder Management  46 non-null     int64
 57  Presentation Skills     46 non-null     int64
 58  Attention to Detail     46 non-null     int64
 59  Agile                   46 non-null     int64
 60  Waterfall               46 non-null     int64
 61  UAT                     46 non-null     int64
 62  Requirement Gathering   46 non-null     int64
 63  Documentation           46 non-null     int64
 64  SaaS Metrics            46 non-null     int64
 65  Financial Modeling      46 non-null     int64
 66  GAAP/IFRS               46 non-null     int64
dtypes: int64(66), object(1)
memory usage: 24.2+ KB
None

## Cleaning the dataset

In [14]:
# Drop columns where the frequency of "1" is less than 5
df_cleaned = df.drop(columns=[col for col in df.columns if col != 'Job Description' and df[col].sum() < 5])

# df_cleaned.head()

# Drop all rows where all columns are "0"
df_cleaned = df_cleaned.loc[~(df_cleaned.iloc[:, 1:] == 0).all(axis=1)]

df_cleaned

,Job Description,Python,R,SQL,Tableau,Power BI,Machine Learning,Predictive Modeling,Excel,ETL,Data Cleaning,Statistics,Analytical Thinking,Problem Solving,Communication,Stakeholder Management,Presentation Skills,Attention to Detail,Documentation
0,Job 1,0,0,1,0,0,0,0,1,1,0,1,1,1,1,1,1,1,1
1,Job 2,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,1
2,Job 3,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0
3,Job 4,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
4,Job 5,1,1,1,1,1,0,0,1,0,0,1,1,0,1,1,0,1,1
5,Job 6,1,1,1,1,1,0,0,1,0,0,1,0,1,1,1,0,1,0
6,Job 7,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,0,1,1
7,Job 8,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0
8,Job 9,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,0,0
9,Job 10,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0
10,Job 11,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0
12,Job 13,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,0
13,Job 14,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
14,Job 15,1,1,1,1,1,0,0,1,0,0,1,1,0,1,1,0,1,1
15,Job 16,0,0,0,0,0,0,1,1,0,0,1,1,0,1,0,0,1,0
16,Job 17,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0
17,Job 18,0,0,1,0,1,0,0,1,0,0,1,1,0,1,1,0,0,0
18,Job 19,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
19,Job 20,1,0,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,0
20,Job 21,1,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0
21,Job 22,1,1,1,1,1,0,1,1,0,0,1,0,1,0,0,0,0,0
22,Job 23,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,1,0
23,Job 24,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1
24,Job 25,1,1,1,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0
25,Job 26,0,0,0,0,0,1,0,1,0,0,0,0,1,1,0,0,1,0
26,Job 27,1,1,1,1,1,1,0,1,0,1,1,1,0,1,0,0,0,0
27,Job 28,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
28,Job 29,1,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,0
29,Job 30,1,0,1,0,0,0,0,1,0,1,1,1,1,1,0,1,0,0
30,Job 31,1,0,1,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0
31,Job 32,1,0,1,0,1,0,0,1,1,1,0,0,1,0,0,0,1,0
32,Job 33,1,0,1,0,1,0,0,1,0,0,1,1,0,1,1,0,1,0
33,Job 34,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
34,Job 35,1,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
35,Job 36,1,1,1,1,1,1,0,1,0,0,1,1,0,1,1,0,0,0
36,Job 37,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
37,Job 38,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
38,Job 39,1,0,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0
39,Job 40,1,1,1,1,1,0,0,1,0,0,1,0,0,1,0,0,0,1
40,Job 41,0,0,0,1,1,0,0,1,1,0,0,0,0,1,1,1,0,0
41,Job 42,0,0,1,0,1,0,0,1,0,0,0,1,0,1,1,0,0,1
42,Job 43,0,1,1,0,1,0,0,0,0,0,0,1,0,0,1,0,1,1